/**
 * sync-hosts.mjs —— 从 hosts.mjs（唯一事实源）下发全部宿主声明写点。
 *
 * 以 dsh-input-traffic/scripts/sync-hosts.mjs（P2 定型版）为底，按本仓改编
 * （_tools/host-compat README §2 改编清单）：
 * 1. peer **保持 optional**（与 input-traffic 的必需化相反，见 hosts.mjs 头注释）：
 *    三项宿主子包 peer 全枚举写入，peerDependenciesMeta.optional 原样保留并
 *    校验在位；`@deepseek-ai/cordis` 保持必需 `^4.0.1` 不动。
 * 2. 写点载体：package.json `engines.dsh` + `dsh.plugin.json` `engines.dsh`
 *    （本仓无双写 `dsh.engines`）+ manifest version 镜像（4.2.0-beta.7 落后
 *    package.json 的漂移由本脚本一并收敛）。
 * 3. **四语 README** 管理块：本仓语言集为 README.md（英文）/ README.zh.md /
 *    README.ja.md / README.ko.md。INSTALL×4 经查无版本相关句（2026-10-05
 *    全文核对），不设托管块。
 *
 * 双模式：默认只校验（exit 1 = 有漂移）；`--write` 实际写盘。
 * 用法：node scripts/sync-hosts.mjs [--write]
 */
import { readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import assert from 'node:assert/strict'
import { supportedHosts, peerRange, developmentHost, hostPeerPackages } from './hosts.mjs'

const ROOT = new URL('..', import.meta.url)
const write = process.argv.includes('--write')
const read = (rel) => readFile(new URL(rel, ROOT), 'utf8')

// ── 0. hosts.mjs 自检 ────────────────────────────────────────────────────────
const RC_RE = /^\d+\.\d+\.\d+-rc\.\d+$/
assert(supportedHosts.length > 0, 'supportedHosts 不得为空')
assert.equal(new Set(supportedHosts).size, supportedHosts.length, 'supportedHosts 有重复项')
for (const v of supportedHosts) assert(RC_RE.test(v), `非 rc 版本混入枚举: ${v}（本插件只收 rc）`)
assert(supportedHosts.includes(developmentHost), 'developmentHost 必须在 supportedHosts 内')

// ── 1. package.json：engines.dsh + peerDependencies（宿主子包，全枚举，保持 optional） ──
const pkgUrl = new URL('package.json', ROOT)
const pkgOriginal = await read('package.json')
const pkg = JSON.parse(pkgOriginal)
pkg.engines ??= {}
pkg.engines.dsh = peerRange
pkg.peerDependencies ??= {}
for (const name of hostPeerPackages) {
  // 枚举串即白名单：宿主运行时闸门把每个 dsh-* peer 对着宿主版本做全枚举
  // 匹配，枚举外宿主在挂载预检即拒。optional 只影响宿主外的独立安装。
  pkg.peerDependencies[name] = peerRange
}
pkg.peerDependenciesMeta ??= {}
for (const name of hostPeerPackages) {
  assert(pkg.peerDependenciesMeta[name]?.optional === true, `${name} 的 peerDependenciesMeta.optional 必须保持 true（独立 CLI 安装路径依赖它），缺失请手工补回`)
}
if (Object.keys(pkg.peerDependenciesMeta).length === 0) delete pkg.peerDependenciesMeta
const pkgExpected = JSON.stringify(pkg, null, 2) + '\n'

// ── 2. dsh.plugin.json：engines.dsh + manifest version 同步 ─────────────────
const pluginJsonUrl = new URL('dsh.plugin.json', ROOT)
const pluginOriginal = await read('dsh.plugin.json')
const manifest = JSON.parse(pluginOriginal)
manifest.engines ??= {}
manifest.engines.dsh = peerRange
manifest.version = pkg.version // version 以 package.json 为准，manifest 只镜像
const manifestExpected = JSON.stringify(manifest, null, 2) + '\n'

// ── 3. 四语 README：管理块（支持清单 + 运行时已验证清单） ────────────────────
const BEGIN = '<!-- host-compat:begin — generated by scripts/sync-hosts.mjs from scripts/hosts.mjs; DO NOT EDIT -->'
const END = '<!-- host-compat:end -->'
const versionList = supportedHosts.map((v) => `\`${v}\``).join(' ')
const linesPerLang = {
  'README.md': [
    `- **Supported DSH hosts:** ${versionList} (${supportedHosts.length} rc releases across lines 0.1.0 / 0.1.1 / 0.1.2 / 0.1.5 / 0.1.7 / 0.2.0)`,
  ],
  'README.zh.md': [
    `- **支持的 DSH 宿主：** ${versionList}（覆盖 0.1.0 / 0.1.1 / 0.1.2 / 0.1.5 / 0.1.7 / 0.2.0 六条线共 ${supportedHosts.length} 个 rc）`,
  ],
  'README.ja.md': [
    `- **対応する DSH ホスト:** ${versionList}（0.1.0 / 0.1.1 / 0.1.2 / 0.1.5 / 0.1.7 / 0.2.0 の ${supportedHosts.length} rc）`,
  ],
  'README.ko.md': [
    `- **지원하는 DSH 호스트:** ${versionList} (0.1.0 / 0.1.1 / 0.1.2 / 0.1.5 / 0.1.7 / 0.2.0 라인의 ${supportedHosts.length}개 rc)`,
  ],
}
// 矩阵跑绿清单（.compat-results/verified.json，由 scripts/test-host-compat.mjs 写出）
const verifiedUrl = new URL('.compat-results/verified.json', ROOT)
if (existsSync(verifiedUrl)) {
  const { verified = [] } = JSON.parse(await readFile(verifiedUrl, 'utf8'))
  if (verified.length > 0) {
    const list = verified.map((v) => `\`${v}\``).join(', ')
    linesPerLang['README.md'].push(`- **Runtime-verified:** ${list} — evidence in \`.compat-results/\``)
    linesPerLang['README.zh.md'].push(`- **运行时已验证：** ${list}（证据见 \`.compat-results/\`）`)
    linesPerLang['README.ja.md'].push(`- **ランタイム検証済み:** ${list}（証跡は \`.compat-results/\`）`)
    linesPerLang['README.ko.md'].push(`- **런타임 검증됨:** ${list} (증적은 \`.compat-results/\`)`)
  }
}
const readmeProblems = []
for (const [file, lines] of Object.entries(linesPerLang)) {
  const block = `${BEGIN}\n${lines.join('\n')}\n${END}`
  const url = new URL(`../${file}`, import.meta.url)
  const content = await readFile(url, 'utf8')
  const beginAt = content.indexOf(BEGIN)
  if (beginAt === -1) {
    // 插入点：第一个 `## ` 二级标题前（四语结构一致）
    const at = content.search(/^## /m)
    assert(at !== -1, `${file} 找不到插入锚点（第一个二级标题）`)
    if (write) {
      await writeFile(url, content.slice(0, at) + block + '\n\n' + content.slice(at))
      console.log(`write  ${file}: 插入管理块`)
    } else {
      readmeProblems.push(`${file} 缺少 host-compat 管理块`)
    }
    continue
  }
  const endAt = content.indexOf(END, beginAt)
  assert(endAt !== -1, `${file} 管理块缺少 end 标记`)
  const current = content.slice(beginAt, endAt + END.length)
  if (write) {
    if (current !== block) {
      await writeFile(url, content.slice(0, beginAt) + block + content.slice(endAt + END.length))
      console.log(`write  ${file}: 更新管理块`)
    } else {
      console.log(`ok     ${file}: 管理块已是最新`)
    }
  } else if (current !== block) {
    readmeProblems.push(`${file} 管理块内容需要同步`)
  } else {
    console.log(`ok     ${file}: 管理块已是最新`)
  }
}

// ── 4. 汇总校验/写盘 ────────────────────────────────────────────────────────
if (write) {
  if (pkgOriginal !== pkgExpected) {
    await writeFile(pkgUrl, pkgExpected)
    console.log('write  package.json (engines.dsh + peerDependencies 全枚举)')
  } else console.log('ok     package.json')
  if (pluginOriginal !== manifestExpected) {
    await writeFile(pluginJsonUrl, manifestExpected)
    console.log('write  dsh.plugin.json (engines.dsh + version)')
  } else console.log('ok     dsh.plugin.json')
  console.log('done   --write 完成')
} else {
  const jsonDrift =
    (pkgOriginal !== pkgExpected ? ['package.json (engines.dsh / peerDependencies)'] : []).concat(
      pluginOriginal !== manifestExpected ? ['dsh.plugin.json (engines.dsh / version)'] : [],
    )
  if (jsonDrift.length === 0 && readmeProblems.length === 0) {
    console.log('ok     全部写点与 hosts.mjs 一致')
  } else {
    for (const p of [...jsonDrift, ...readmeProblems]) console.error(`drift  ${p}`)
    console.error('\n运行 node scripts/sync-hosts.mjs --write 修复')
    process.exit(1)
  }
}
